### ISSUE TITLE
Commentaires du projet - Elisa & Coralie

### ISSUE THREAD

**Issue by coralie39** [Syph4x/Bilan_conso#1]
NETTOYAGE DES TABLES : 

- Vous mettez des chemins d'accès qui sont valables uniquement sur votre ordinateur et non sur ceux des autres.
Par exemple, remplacer cette commande :
conso_commune <- read.csv("C://Users//sguest//Desktop//projet R avance//jeu de donnee//Tables de donnees Conso//conso-commune.csv",sep = ";",encoding = "UTF-8")
par : 
conso_commune <- read.csv("consommation-electrique-par-secteur-dactivite-commune.csv",sep = ";",encoding = "UTF-8")
en mettant tous les fichiers dans un même dossier.
Il faut faire cela pour le traitement 1 et le traitement 2.

- Dans le traitement 2, il y a des erreurs de code. Par exemple, les commandes suivantes : 
nom_department_c <- sapply(departement$nom_departement,FUN = clean_Names)
nom_commune_c <- sapply(commune$nom_commune,FUN = clean_Names)
sont à remplacer par :
nom_department_c <- sapply(departement_c$nom_departement,FUN = clean_Names)
nom_commune_c <- sapply(commune_c$nom_commune,FUN = clean_Names)

- Il faudrait optimiser le code pour le nettoyage des 6 tables car il faut 2h juste pour effectuer traitement 1 + traitement 2.

SHINY : 

- Le titre de l'application n'apparaît pas en entier.

- Il n'y a pas d'onglets "Résumé" et "Détails".

- Lors de la sélection des régions, il y a un problème : certaines d'entre elles apparaissent en minuscules et en majuscules, et d'autres en double. Exemple : Provence-Alpes-Cote-d'Azur et PROVENCE ALPES COTE D AZUR

- Pour les régions, il y a de nombreuses erreurs. On ne peut pas visualiser les graphiques. 
Exemple d'erreur : object 'conso_totale__mwh_' not found

- La moyenne en France vaut 0 peu importe la région ou le département choisi. Il y a donc un problème dans les calculs. De même, pour les communes.

- Pas d'unités dans les valuebox. Revoir l'esthétique pour plus de visibilité.

- Pour les communes, il y a des erreurs. On ne peut rien voir.

- Dans les datatables, il n'y a pas la colonne "Moyenne France".

- Certaines fonctions dans votre code ne sont pas utiles. Par exemple : 
Cette fonction n'est pas utilisée : 
     x <- reactive({
    return(input$type)
  })
Celle-ci ne sert à rien. Vous pouvez utiliser directement input$maille dans votre code.
    y <- reactive({
        return(input$maille)
    })

REMARQUES GENERALES : 

- Optimiser le nettoyage des tables.
- Beaucoup d'erreurs de code à corriger qui nuisent l'utilisation de l'application.
- Attention aux fautes d'orthographe.
- Revoir l'esthétique et attention à la lisibilité des graphiques.
- Attention à la lisibilité du code. Pensez à utiliser "Reformat Code" dans l'onglet "Code".

**Comment by Syph4x** [comment]
Bonsoir Coralie,
Merci pour le retour, j'en prends note.
Cordialement.
S Bourennani
